# Generated by Django 4.0.1 on 2022-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('slug', models.SlugField(max_length=52)),
                ('turn_left', models.FloatField(help_text='Turn Camera to left')),
                ('turn_right', models.FloatField(help_text='Turn Camera to Right')),
            ],
        ),
    ]
