# Generated by Django 4.0.1 on 2022-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='slug',
            field=models.SlugField(blank=True, max_length=52),
        ),
        migrations.AlterField(
            model_name='cam',
            name='turn_left',
            field=models.FloatField(blank=True, help_text='Turn Camera to left'),
        ),
        migrations.AlterField(
            model_name='cam',
            name='turn_right',
            field=models.FloatField(blank=True, help_text='Turn Camera to Right'),
        ),
    ]
