# Generated by Django 4.0.1 on 2022-02-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_cam_turn_left_alter_cam_turn_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
